name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch git branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          cmd: release # will run `yarn release` command

