name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: macOS-latest
    steps:
      - name: setup node
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      
      - name: checkout    
      - uses: actions/checkout@v2
      
      - name: yarn install
        run: |
          yarn install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn release
      


