name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch git branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release

